---
title: "Generating and evaluating synthetic data in `R`"
date: 2025-19-08
page-navigation: true
citation:
  type: "webpage"
  title: "Generating and evaluating synthetic data in R"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/synthetic-data-tutorial/
  doi: "TODO: DOI HERE"
author:
  - name: Thom Benjamin Volker
    roles: [conceptualization, formal analysis, funding acquisition, investigation, methodology, project administration, software, resources, validation, visualization, writing - original draft, writing - editing & review]
    degrees: MSc.
    affiliation: 
      - id: uu
        name: Utrecht University
        department: Methodology and Statistics
        city: Utrecht
        country: The Netherlands
      - id: cbs
        name: Statistics Netherlands
        department: Methodology
        city: The Hague
        country: The Netherlands
    orcid: 0000-0002-2408-7820
google-scholar: true
---


# Contributors

This site was authored by Thom Volker, and edits/contributions were made by Malika Ihle. <!-- TODO: Expand contributing authors -->

# Licenses

The overall project is available under the **[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)** license found at [LICENSE](LICENSE.md); all code without any narrative text is also (at your option) available under the **[CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/)** license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

# Notes

This tutorial was primarily written in 2025 using `R` version `4.5.0`. Major changes to `R` can be found at the [R website](https://cran.r-project.org/) for the most up-to-date information, and to confirm that our tutorial is not out-of-date. 

