---
title: "Welcome to the synthetic data tutorial!"
page-navigation: true
---

# Tutorial Overview

This **self-paced tutorial** will introduce you to the generation and evaluation of synthetic data. 
Synthetic data is generated data that can be used as an alternative to privacy-sensitive data, for example to enhance open science practices. 
Advantages of open (synthetic) data are numerous: other researchers can re-run analyses with data that is close to the actual data, which allows them to verify the main results. 
Additionally, open (synthetic) data allows researchers to perform exploratory analyses that may lead to novel hypotheses, and in quite some instances performing such analyses with synthetic data yields rather accurate results.
Moreover, realistic synthetic data can be used in teaching, or for starting with model building when access to the real data is currently still prohibited. 
All in all, synthetic data makes open science practices easier and might spark collaborations with potential data users.


The tutorial focuses on the generation of tabular synthetic data. This precludes the generation of text data or other high-dimensional data sources (fMRI, intensive longitudinal data, etc.). Some extensions to multilevel-data are discussed, but this is not the main goal of the materials. In total, the tutorial is intended to take approximately 2-3 hours to complete, and is split into the following sections:

1.  [Statistical Disclosure Control](sdc/) provides a very brief introduction to methods used to protect individuals’ private information, while keeping the released data useful for analysis.
2.  [Synthetic data: The general idea](synthetic/) conceptually introduces the idea of synthetic data and contains an optional section on coding your own simple synthesizer.
3.  [Generating synthetic data](geneneration/) introduces the idea of synthetic data and outlines how it can be generated in `R`.
4.  [Evaluating synthetic data quality](evaluation/) addresses the privacy-utility trade-off, and discusses how the quality of synthetic data can be evaluated from both sides of this trade-off.
5. [Publishing and using synthetic data](publishing/) discusses when and how to publish synthetic data safely.

At the end of this tutorial, you will know what synthetic data is and why it is useful, have experience with generating synthetic data, and know how to think about whether the data is fit for release. 


::: {.callout-tip title="Recommended Software"}
This tutorial assumes you have the following software installed:

- A recent version of [R (>= 4.1.0)](https://cran.r-project.org/)
- [RStudio](https://posit.co/downloads/)

Also, the tutorial requires the following `R` packages:

- [`synthpop`](https://synthpop.org.uk/get-started.html)
- [`densityratio`](https://thomvolker.github.io/densityratio)
- [`mvtnorm`](https://mvtnorm.r-forge.r-project.org/)

Before starting, please install the required packages as follows.

```{r}
#| label: install-packages
#| eval: false

install.packages("synthpop")
install.packages("densityratio")
install.packages("mvtnorm")
```

:::
